[project]
name = "tp-dao"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cors>=1.0.1",
    "flask-cors>=6.0.1",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "pytest>=9.0.0",
]
